math(EXPR platform_bits "${CMAKE_SIZEOF_VOID_P} * 8")
#set(platform_dir ${CMAKE_SYSTEM_NAME}${platform_bits}-${CMAKE_CXX_COMPILER_ID}${CMAKE_CXX_COMPILER_VERSION})
set(platform_dir ${CMAKE_SYSTEM_PROCESSOR}-${CMAKE_CXX_COMPILER_ID}_${CMAKE_HOST_SYSTEM_NAME}-GCC_${CMAKE_CXX_COMPILER_VERSION}-${CMAKE_BUILD_TYPE})

foreach(config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    foreach(var CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${config} CMAKE_LIBRARY_OUTPUT_DIRECTORY_${config} CMAKE_RUNTIME_OUTPUT_DIRECTORY_${config})
        set(${var} "${CMAKE_BINARY_DIR}/${platform_dir}-${config}")
        string(TOLOWER "${${var}}" ${var})
    endforeach()
endforeach()

message (STATUS "AOL ${CMAKE_SYSTEM_PROCESSOR}-${CMAKE_CXX_COMPILER_ID}_${CMAKE_HOST_SYSTEM_NAME}-GCC_${CMAKE_CXX_COMPILER_VERSION}-${CMAKE_BUILD_TYPE}")